### PR TITLE
Chore: remove unneeded interface methods

### PR DESCRIPTION
**Pull request by stevennevins**
https://github.com/Layr-Labs/eigenlayer-middleware/issues/33

### CODE REVIEW

**Review by ChaoticWalrus — APPROVED** [review]
Works for me.
We aren't using these functions in M2 so should be fine to delete; they can be added back later.

**Comment by samlaf** [comment]
Thanks @stevennevins ! Are you planning to update the ServiceManagerBase in another PR? If not, can we include it here (it was part of the issue #33 )

**Comment by samlaf** [comment]
Thanks for the quick changes @ChaoticWalrus !!
As we've talked offline, question now is whether this ServiceManagerBase is even worth keeping at all. Don't have enough contracts experience to make a good decision here, so will let you guys decide, but ideal solution would be *actually* useful for AVS devs, without getting more random requirements in their way.

Perhaps we can merge this PR and discuss this issue separately?

**Comment by stevennevins** [comment]
> Thanks for the quick changes @ChaoticWalrus !! As we've talked offline, question now is whether this ServiceManagerBase is even worth keeping at all. Don't have enough contracts experience to make a good decision here, so will let you guys decide, but ideal solution would be _actually_ useful for AVS devs, without getting more random requirements in their way.
> 
> Perhaps we can merge this PR and discuss this issue separately?

I'm pro removing anything that seems like bloat and isn't immediately useful

**Comment by ChaoticWalrus** [comment]
> I'm pro removing anything that seems like bloat and isn't immediately useful

After reviewing ServiceManagerBase, I think it's pretty close to an empty shell at the moment. Would be fine deleting it, especially if AVS team isn't finding it useful.

**Pull request merged**
