### PR TITLE
chore: less restrictive pragma

### PR DESCRIPTION
**Pull request by stevennevins**

### CODE REVIEW

**Comment by samlaf** [comment]
This would be super useful. For eg integrating our contracts with risc0 contracts was a pain because they had their contracts using ^0.8.21

**Comment by RonTuretzky** [comment]
bumping for hype 🔥

**Review by wadealexc — CHANGES_REQUESTED** [review]
Just needs a submodule update for the core repo, and then this is good to go!

**Review by wadealexc — APPROVED** [review]
(pending submodule update, LGTM otherwise)

**Pull request merged**
