### PR TITLE
feat: public immutable vars in ServiceManagerBase

### PR DESCRIPTION
**Pull request by ghost**
This PR updates the visibility of three internal state variables (_registryCoordinator, _delegationManager, and _stakeRegistry) to public. Additionally, immutable getters are introduced for these variables.

### CODE REVIEW

**Comment by wadealexc** [comment]
Thanks for the PR. We just updated these to be internal - do you need them to be public for some reason?

**Comment by ny-alt** [comment]
Yes, it is for the getters.

**Comment by ghost** [comment]
> Thanks for the PR. We just updated these to be internal - do you need them to be public for some reason?

Yes, it's for the getters in my case.

**Comment by wadealexc** [comment]
i see - i think `ServiceManagerBase` is meant to be something you inherit from. Maybe you could create a `ServiceManager is ServiceManagerBase` for your usecase, and expose the variables there?

Maybe we should mark `ServiceManagerBase` as `abstract` :sweat:

**Comment by ghost** [comment]
I understand that ServiceManagerBase is meant for inheritance. 

What are the cons of making those variables as `public`?

**Comment by wadealexc** [comment]
I think someone on our team was making a service manager contract that also inherits from `BLSSignatureChecker`, and there were some issues with shadowing/overloading.

**Comment by wadealexc** [comment]
Sorry, I'm not 100% sure -- this happened while I was on vacation :D

**Comment by ghost** [comment]
I see. But It no longer inherits `BLSSignatureChecker`.

**Comment by wadealexc** [comment]
Correct - they wanted to make a contract like this:

`contract ServiceManager is ServiceManagerBase, BLSSignatureChecker`

**Comment by wadealexc** [comment]
Going to close this for now, but thank you for the PR.

Also if you want to chat about anything else on our Discord (rather than over PR comments), we have a `#talk-smart-contracts` channel that's perfect for this! https://discord.gg/wfG9Kr8h

**Pull request closed without merging**
